FROM alpine:latest

RUN apk update

RUN apk upgrade

RUN apk add \
    nginx \
    php \
    php-fpm \
    php-mysqli \
    php-json \
    php-openssl \
    php-curl \
    php-zlib \
    php-phar \
    php-mbstring \
    php-session \
    php-iconv \
    php-dom \
    php-ctype \
    php-fileinfo \
    php-tokenizer \
    wget \
    unzip \
    nano \
    curl && \
    mkdir -p /var/www/html && \
    mkdir -p /run/nginx

COPY ./assets/phpmyadmin.zip /tmp/phpmyadmin.zip
RUN unzip /tmp/phpmyadmin.zip -d /var/www/html/ && \
    rm /tmp/phpmyadmin.zip

RUN chown -R nginx:nginx /var/www/html && \
    find /var/www/html -type d -exec chmod 755 {} \; && \
    find /var/www/html -type f -exec chmod 644 {} \; && \
    find /var/www/html -type f -exec chmod +x {} \;

RUN chown -R nginx:nginx /var/www/html/tmp && \
    chmod 755 /var/www/html/tmp

EXPOSE 80

CMD ["sh", "-c", "php-fpm83 && nginx -g 'daemon off;'"]
