services:
  nginx:
    image: nginx:alpine
    container_name: ${NAME}_nginx
    volumes:
      - ./nginx/site.conf:/etc/nginx/templates/default.conf.template:ro
      - ${VOLUME_PREFIX}/logs/nginx:/var/log/nginx:rw
      - ${VOLUME_PREFIX}/database/nginx:/var/cache/nginx:rw
      - ${VOLUME_PREFIX}/root:/var/www/html:ro
    environment:
      - NGINX_HOST=${DOMAIN_NAME}
    ports:
      - "127.0.0.1:${PORT_HTTP}:80"
    depends_on:
      - php-fpm
    networks:
      - my_network

  mariadb:
    image: mariadb
    container_name: ${NAME}_db
    volumes:
      - ${VOLUME_PREFIX}/database/mariadb:/var/lib/mysql:rw
      - ./config/mariadb.cnf:/etc/mysql/my.cnf:ro
      - ${VOLUME_PREFIX}/logs/mariadb:/var/log/mysql:rw
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    networks:
      - my_network

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: ${NAME}_php
    volumes:
      - ${VOLUME_PREFIX}/root:/var/www/html:rw
      - ${VOLUME_PREFIX}/logs/php:/var/log/php:rw
      - ./config/php.ini:/usr/local/etc/php/php.ini:ro
    depends_on:
      - mariadb
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
    networks:
      - my_network

  phpmyadmin:
    build:
      context: .
      dockerfile: Dockerfile-phpmyadmin
    container_name: ${NAME}_phpmyadmin
    volumes:
      - ./nginx/phpmyadmin.conf:/etc/nginx/http.d/default.conf:ro
      - ${VOLUME_PREFIX}/database/phpmyadmin:/var/www/html/tmp:rw
      - ${VOLUME_PREFIX}/logs/phpmyadmin:/var/log/php83:rw
      - ./config/php.ini:/etc/php83/php.ini:ro
    ports:
      - "127.0.0.1:${PORT_PHPMYADMIN}:80"
    depends_on:
      - mariadb
    networks:
      - my_network

  filemanager:
    build:
      context: .
      dockerfile: Dockerfile-filemanager
    container_name: ${NAME}_filemanager
    volumes:
      - ./assets/filemanager/index.php:/var/www/filemanager/index.php:ro
      - ./assets/filemanager/translation.json:/var/www/filemanager/translation.json:ro
      - ./config/filemanager.php:/var/www/filemanager/config.php:ro
      - ./nginx/filemanager.conf:/etc/nginx/http.d/default.conf:ro
      - ${VOLUME_PREFIX}/.env:/var/www/filemanager/.env:ro
    ports:
      - "127.0.0.1:${PORT_FILEMANAGER}:80"
    depends_on:
      - php-fpm
    environment:
      FILEMANAGER_USERNAME: ${FILEMANAGER_USERNAME}
      FILEMANAGER_PASSWORD: ${FILEMANAGER_PASSWORD}
      FILEMANAGER_PATH: ${FILEMANAGER_PATH}
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
