FROM alpine:latest 

RUN apk update --no-cache && \
    apk upgrade --no-cache && \
    apk add --no-cache \
    nginx \
    php \
    php-fpm \
    php-mysqli \
    php-json \
    php-openssl \
    php-curl \
    php-zlib \
    php-phar \
    php-mbstring \
    php-session \
    php-iconv \
    php-dom \
    php-ctype \
    php-fileinfo \
    php-opcache \
    php-zip \
    php-tokenizer \
    wget \
    unzip \
    nano \
    pcre2 \
    pcre2-dev \
    autoconf \
    gcc \
    g++ \
    make \
    curl \
  && mkdir -p /var/www/html \
  && mkdir -p /run/nginx

WORKDIR /var/www/html
EXPOSE 80

CMD ["sh", "-c", "php-fpm83 && nginx -g 'daemon off;'"]
