FROM php:8.1-fpm-alpine

RUN apk update --no-cache && \
    apk upgrade --no-cache && \
    apk add --no-cache \
    gcc \
    g++ \
    cmake \
    make \
    autoconf \
    libedit \
    openssl \
    openssl-dev \
    libedit-dev \
    libcurl \
    curl-dev \
    libtool \
    pkgconfig \
    zlib-dev \
    build-base \
    freetype-dev \
    libjpeg-turbo-dev \
    libpng-dev \
    libzip-dev \
    zip \
    unzip \
    libxml2-dev \
    curl \
    wget \
    git \
    readline-dev \
    readline \
    bash \
    nano \
    icu-dev \
    libsodium \
    oniguruma-dev \
    gnu-libiconv \
    gnu-libiconv-dev \
    ncurses-dev \
    ncurses \
    gettext-dev \
    gettext \
    libc6-compat \
    libudev-zero \
    linux-headers \
    shadow \
    icu-data-full \
    php81-pecl-xdebug \
    php81-pecl-redis \
    php81-gettext \
    php81-curl \
    php81-dom \
    php81-fileinfo \
    php81-gd \
    php81-mysqli \
    php81-pdo \
    php81-pdo_mysql \
    php81-zip \
    php81-intl \
    php81-mbstring \
    php81-soap \
    php81-xml \
    php81-opcache \
    pcre2 \
    pcre2-dev \
    autoconf \
    gcc \
    g++ \
    make \
    --repository https://nl.alpinelinux.org/alpine/edge/testing --allow-untrusted

RUN apk add --no-cache postfix-pcre

RUN docker-php-ext-install mysqli

COPY ./assets/ioncube_loader_lin_8.1.so /usr/local/lib/php/extensions/no-debug-non-zts-20210902/ioncube_loader_lin_8.1.so
RUN echo "zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20210902/ioncube_loader_lin_8.1.so" > /usr/local/etc/php/conf.d/00-ioncube.ini

COPY ./assets/ixed.8.1.lin /usr/local/lib/php/extensions/no-debug-non-zts-20210902/ixed.8.1.lin
RUN echo "zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20210902/ixed.8.1.lin" > /usr/local/etc/php/conf.d/00-sourceguardian.ini

# RUN echo "extension=mysqli" > /usr/local/etc/php/conf.d/mysqli.ini

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer


RUN cp /usr/lib/php81/modules/* /usr/local/lib/php/extensions/no-debug-non-zts-20210902/

RUN chown -R www-data:www-data /usr/local/lib/php/extensions

COPY ./config/set_permissions.sh /usr/local/bin/set_permissions.sh
RUN chmod +x /usr/local/bin/set_permissions.sh

WORKDIR /var/www/html
EXPOSE 9000

# CMD ["sh", "-c" "/usr/local/bin/set_permissions.sh & php-fpm"]
CMD ["php-fpm"]
