FROM alpine:latest

RUN apk update --no-cache && \
    apk upgrade --no-cache && \
    apk add --no-cache \
    nginx \
    php \
    php-fpm \
    php-mysqli \
    php-json \
    php-openssl \
    php-curl \
    php-zlib \
    php-phar \
    php-mbstring \
    php-session \
    php-iconv \
    php-dom \
    php-ctype \
    php-fileinfo \
    php-tokenizer \
    wget \
    unzip \
    nano \
    curl && \
    mkdir -p /var/www/html && \
    mkdir -p /run/nginx

COPY ./assets/phpmyadmin.zip /tmp/phpmyadmin.zip
COPY ./config/phpmyadmin.php /var/www/html/config.inc.php

RUN unzip /tmp/phpmyadmin.zip -d /var/www/html/ && \
    rm /tmp/phpmyadmin.zip && \
    chown -R nginx:nginx /var/www/html && \
    find /var/www/html -type d -exec chmod 755 {} \; && \
    find /var/www/html -type f -exec chmod 644 {} \; && \
    chmod 644 /var/www/html/config.inc.php

WORKDIR /var/www/html
EXPOSE 80

CMD ["sh", "-c", "chown -R nginx:nginx /var/www/html/tmp && chmod -R 777 /var/www/html/tmp && php-fpm83 && nginx -g 'daemon off;'"]
