services:
  nginx:
    image: nginx:alpine
    container_name: ${NAME}_nginx
    volumes:
      - ./nginx/site.conf:/etc/nginx/templates/default.conf.template
      - ${VOLUME_PREFIX}/logs/nginx:/var/log/nginx
      - ${VOLUME_PREFIX}/root:/var/www/html
    environment:
      - NGINX_HOST=${DOMAIN_NAME}
    ports:
      - "${PORT_HTTP}:80"
    depends_on:
      - php-fpm
    networks:
      - my_network
    command: sh -c "adduser -S -G www-data www-data && chown -R www-data:www-data /var/www/html"

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: ${NAME}_php
    volumes:
      - ${VOLUME_PREFIX}/root:/var/www/html:rw
      - ${VOLUME_PREFIX}/logs/php:/var/log/php
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
    networks:
      - my_network

  mariadb:
    image: mariadb
    container_name: ${NAME}_db
    volumes:
      - ${VOLUME_PREFIX}/database/mariadb:/var/lib/mysql
      - ./config/mariadb.cnf:/etc/mysql/my.cnf
      - ${VOLUME_PREFIX}/logs/mariadb:/var/log/mysql
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  phpmyadmin:
    build:
      context: .
      dockerfile: Dockerfile-phpmyadmin
    container_name: ${NAME}_phpmyadmin
    volumes:
      - ./nginx/phpmyadmin.conf:/etc/nginx/http.d/default.conf
      - ${VOLUME_PREFIX}/database/phpmyadmin:/var/www/html/tmp:rw
      - ${VOLUME_PREFIX}/logs/phpmyadmin:/var/log/php
      - ./config/php.ini:/etc/php83/php.ini:ro
      # - ./config/phpmyadmin.php:/var/www/html/config.inc.php
    ports:
      - "${PORT_PHPMYADMIN}:80"
    depends_on:
      - mariadb
    networks:
      - my_network

  filemanager:
    build:
      context: .
      dockerfile: Dockerfile-filemanager
    container_name: ${NAME}_filemanager
    volumes:
      - ./assets/filemanager/index.php:/var/www/html/index.php
      - ./assets/filemanager/translation.json:/var/www/html/translation.json
      - ./config/filemanager.php:/var/www/html/config.php
      - ./nginx/filemanager.conf:/etc/nginx/http.d/default.conf
      - ${VOLUME_PREFIX}/root:/var/www/html/root:rw
      - ${VOLUME_PREFIX}/logs/filemanager:/var/log/php
      - ${VOLUME_PREFIX}/.env:/var/www/html/.env:ro
      - ./config/php.ini:/etc/php83/php.ini:ro
    ports:
      - "${PORT_FILEMANAGER}:80"
    depends_on:
      - mariadb
    environment:
      FILEMANAGER_USERNAME: ${FILEMANAGER_USERNAME}
      FILEMANAGER_PASSWORD: ${FILEMANAGER_PASSWORD}
      FILEMANAGER_PATH: ${FILEMANAGER_PATH}
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
