services:
  nginx:
    image: nginx:alpine
    container_name: ${NAME}_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - ./logs/nginx:/var/log/nginx
      - ./root:/var/www/html
    environment:
      - NGINX_HOST=${DOMAIN_NAME}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
    networks:
      - wp_network

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: ${NAME}_php
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./root:/var/www/html
      - ./logs/php:/var/log/php
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
    networks:
      - wp_network

  mariadb:
    image: mariadb
    container_name: ${NAME}_db
    volumes:
      - ./database/mariadb:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    networks:
      - wp_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:fpm-alpine
    container_name: ${NAME}_phpmyadmin
    volumes:
      # https://github.com/phpmyadmin/phpmyadmin/blob/master/config.sample.inc.php
      - ./nginx-phpmyadmin.conf:/etc/nginx/conf.d/default.conf
      - ./config.inc.php:/etc/phpmyadmin/config.inc.php
    environment:
      PMA_HOST: mariadb
    ports:
      - "8082:80"
    depends_on:
      - mariadb
    networks:
      - wp_network

  filebrowser:
    image: filebrowser/filebrowser
    container_name: ${NAME}_filebrowser
    volumes:
      - ./filebrowser.json:/filebrowser.json
      - ./filebrowser.json:/.filebrowser.json
      - ./database/filemanager/filebrowser.db:/config/filebrowser.db
      - ./logs/filebrowser/filebrowser.log:/config/filebrowser.log
      - ./root:/srv
    ports:
      - "8081:80"
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - wp_network

networks:
  wp_network:
    driver: bridge
