FROM php:8.1-fpm-alpine

RUN apk --no-cache add \
    freetype-dev \
    libjpeg-turbo-dev \
    libpng-dev \
    libzip-dev \
    libxml2-dev \
    curl \
    wget \
    git \
    bash \
    nano \
    icu-dev \
    libsodium \
    oniguruma-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) \
       gd \
       mysqli \
       pdo \
       pdo_mysql \
       zip \
       intl \
       mbstring \
       soap \
       xml \
       opcache \
       iconv \
       json \
       filter \
       hash \
       curl \
       dom \
       fileinfo \
       readline \
       gettext \
       date \
    && pecl install xdebug redis \
    && docker-php-ext-enable xdebug redis \
    && apk del curl wget git bash nano

RUN wget -qO /tmp/ioncube.tar.gz https://downloads.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz && \
    tar -xzf /tmp/ioncube.tar.gz -C /tmp && \
    mv /tmp/ioncube/ioncube_loader_lin_8.1.so /usr/local/lib/php/extensions/no-debug-non-zts-20210902/ && \
    echo "zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20210902/ioncube_loader_lin_8.1.so" > /usr/local/etc/php/conf.d/00-ioncube.ini && \
    rm -rf /tmp/ioncube /tmp/ioncube.tar.gz

RUN wget -qO /tmp/sourceguardian.tar.gz https://www.sourceguardian.com/sourceguardian-php-8.1.tar.gz && \
    tar -xzf /tmp/sourceguardian.tar.gz -C /tmp && \
    mv /tmp/sourceguardian/extension/sourceguardian.so /usr/local/lib/php/extensions/no-debug-non-zts-20210902/ && \
    echo "zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20210902/sourceguardian.so" > /usr/local/etc/php/conf.d/00-sourceguardian.ini && \
    rm -rf /tmp/sourceguardian /tmp/sourceguardian.tar.gz

COPY ./php.ini /usr/local/etc/php/conf.d/php.ini

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN useradd -m -u 1000 phpuser && chown -R phpuser:phpuser /var/www/html

WORKDIR /var/www/html

EXPOSE 9000

CMD ["php-fpm"]
