FROM php:8.1-fpm-alpine

RUN rm -rf /tmp/* /usr/src/php/ext/*

RUN apk --no-cache add \
    autoconf \
    libtool \
    pkgconfig \
    zlib-dev \
    build-base \
    freetype-dev \
    libjpeg-turbo-dev \
    libpng-dev \
    libzip-dev \
    libxml2-dev \
    curl \
    wget \
    git \
    bash \
    nano \
    icu-dev \
    libsodium \
    oniguruma-dev \
    gnu-libiconv \
    gnu-libiconv-dev

RUN docker-php-ext-configure gd --with-freetype --with-jpeg
RUN docker-php-ext-install -j$(nproc) gd
RUN docker-php-ext-install -j$(nproc) mysqli
RUN docker-php-ext-install -j$(nproc) pdo
RUN docker-php-ext-install -j$(nproc) pdo_mysql
RUN docker-php-ext-install -j$(nproc) zip
RUN docker-php-ext-install -j$(nproc) intl
RUN docker-php-ext-install -j$(nproc) mbstring
RUN docker-php-ext-install -j$(nproc) soap
RUN docker-php-ext-install -j$(nproc) xml
RUN docker-php-ext-install -j$(nproc) opcache
RUN docker-php-ext-install -j$(nproc) json
RUN docker-php-ext-install -j$(nproc) filter
RUN docker-php-ext-install -j$(nproc) hash
RUN docker-php-ext-install -j$(nproc) curl
RUN docker-php-ext-install -j$(nproc) dom
RUN docker-php-ext-install -j$(nproc) fileinfo
RUN docker-php-ext-install -j$(nproc) readline
RUN docker-php-ext-install -j$(nproc) gettext
RUN docker-php-ext-install -j$(nproc) date

RUN docker-php-ext-configure iconv --with-iconv=/usr --with-libiconv

RUN pecl install xdebug redis

RUN docker-php-ext-enable xdebug redis

RUN apk del curl wget git bash nano

RUN ls /usr/src/php/ext/opcache/modules/
 
RUN wget -qO /tmp/ioncube.tar.gz https://downloads.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz && \
    tar -xzf /tmp/ioncube.tar.gz -C /tmp && \
    mv /tmp/ioncube/ioncube_loader_lin_8.1.so /usr/local/lib/php/extensions/no-debug-non-zts-20210902/ && \
    echo "zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20210902/ioncube_loader_lin_8.1.so" > /usr/local/etc/php/conf.d/00-ioncube.ini && \
    rm -rf /tmp/ioncube /tmp/ioncube.tar.gz

RUN wget -qO /tmp/sourceguardian.tar.gz https://www.sourceguardian.com/sourceguardian-php-8.1.tar.gz && \
    tar -xzf /tmp/sourceguardian.tar.gz -C /tmp && \
    mv /tmp/sourceguardian/extension/sourceguardian.so /usr/local/lib/php/extensions/no-debug-non-zts-20210902/ && \
    echo "zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20210902/sourceguardian.so" > /usr/local/etc/php/conf.d/00-sourceguardian.ini && \
    rm -rf /tmp/sourceguardian /tmp/sourceguardian.tar.gz

RUN chown -R phpuser:phpuser /usr/local/lib/php/extensions

COPY ./php.ini /usr/local/etc/php/conf.d/php.ini

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN useradd -m -u 1000 phpuser && chown -R phpuser:phpuser /var/www/html

RUN php -v
WORKDIR /var/www/html

EXPOSE 9000

CMD ["php-fpm"]
