FROM alpine:latest

RUN apk update

RUN apk upgrade

RUN apk add \
    nginx \
    php \
    php-fpm \
    php-mysqli \
    php-json \
    php-openssl \
    php-curl \
    php-zlib \
    php-phar \
    php-mbstring \
    php-session \
    php-iconv \
    php-dom \
    php-ctype \
    php-fileinfo \
    php-tokenizer \
    wget \
    unzip \
    nano \
    curl && \
    mkdir -p /var/www/html && \
    mkdir -p /run/nginx && \
    chown -R nginx:nginx /var/www/html

COPY ./tinyfilemanager.zip /tmp/tinyfilemanager.zip
RUN unzip /tmp/tinyfilemanager.zip -d /var/www/html/ && \
    rm /tmp/tinyfilemanager.zip

COPY ./config.inc.php /var/www/html/config.inc.php
RUN chown -R nginx:nginx /var/www/html

RUN sed -i 's/;listen.mode = 0660/listen.mode = 0666/' /etc/php83/php-fpm.d/www.conf && \
    sed -i 's/127.0.0.1:9000/\/var\/run\/php-fpm.sock/' /etc/php83/php-fpm.d/www.conf && \
    sed -i 's/user = nobody/user = nginx/' /etc/php83/php-fpm.d/www.conf && \
    sed -i 's/group = nobody/group = nginx/' /etc/php83/php-fpm.d/www.conf

RUN rm /etc/nginx/http.d/default.conf
COPY ./nginx/filemanager.conf /etc/nginx/http.d/default.conf

EXPOSE 80

CMD ["sh", "-c", "php-fpm83 && nginx -g 'daemon off;'"]
