services:
  nginx:
    image: nginx
    container_name: ${NAME}_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
      - ./root:/var/www/html
    environment:
      - NGINX_HOST=${DOMAIN_NAME}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
    networks:
      - wp_network

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: ${NAME}_php
    volumes:
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./root:/var/www/html
      - ./logs/php:/var/log/php
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
    networks:
      - wp_network

  mariadb:
    image: mariadb:10.6
    container_name: ${NAME}_db
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - wp_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${NAME}_phpmyadmin
    environment:
      PMA_HOST: mariadb
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - wp_network

networks:
  wp_network:
    driver: bridge
